spring:
  datasource:
    url: jdbc:sqlserver://anubhavserver.database.windows.net:1433;database=anubhavdb;user=anubhav123@anubhavserver;password=Anubhav@1234567;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: anubhav123
    password: Anubhav@1234567
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9193


